FROM s_trans_base_image

RUN   apt update -y && apt upgrade -y \
      && wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb \
	  && dpkg -i cuda-keyring_1.1-1_all.deb \
	  && apt-get update && apt-get -y install cuda-toolkit-12-6 \
	  && export PATH=/usr/local/cuda/bin${PATH:+:${PATH}} && export LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
