FROM s_trans_base_image

RUN mkdir -p /service

COPY ./.env /.env
COPY ./src/backend.py /service/backend.py
COPY req_backend.txt /service/req_backend.txt
COPY ./runners/backend.sh /service/backend.sh
RUN chmod +x /service/backend.sh

WORKDIR /service

RUN python3 -m pip install -r req_backend.txt
