FROM ubuntu:22.04
ENV TZ=Europe/London
ENV PYTHONUNBUFFERED=1

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
      && echo $TZ > /etc/timezone \
      && apt-get -y update \
      && apt update && apt upgrade -y \
      && apt-get install -y iputils-ping \
      && apt install software-properties-common -y \
      && add-apt-repository ppa:deadsnakes/ppa \
      && apt -y install python3.10 python3.10-dev python3-venv python3-pip python3-setuptools build-essential libssl-dev \
      && python3.10 -m pip install --upgrade pip --no-cache-dir \
      && apt-get clean && rm -rf /var/lib/apt/lists/* \
      && unlink /usr/bin/python3 && ln -s /usr/bin/python3.10 /usr/bin/python3 \
      && apt update -y && apt upgrade -y && apt install wget -y
